### ISSUE TITLE
Parsing error and hence deployment failing

### ISSUE THREAD

**Issue by vidhyaan** [cloudfoundry/multiapps-controller#1285]
### Description
While deploying an application to cloud foundry I get the below error
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (':' (code 58)): was expecting double-quote to start field name
 at [Source: (String)"{:"app-content-digest"=>"47C2C615EFEF2BAE96FBDE8F1CBED293"}"; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391) ~[jackson-core-2.13.4.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735) ~[jackson-core-2.13.4.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659) ~[jackson-core-2.13.4.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1860) ~[jackson-core-2.13.4.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:962) ~[jackson-core-2.13.4.jar:?]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:582) ~[jackson-databind-2.13.4.2.jar:?]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437) ~[jackson-databind-2.13.4.2.jar:?]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.13.4.2.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.4.2.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.4.2.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.4.2.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612) ~[jackson-databind-2.13.4.2.jar:?]
	at org.cloudfoundry.multiapps.common.util.JsonUtil.fromJson(JsonUtil.java:142) ~[multiapps-common-2.12.0.jar:?]
	at org.cloudfoundry.multiapps.common.util.JsonUtil.convertJsonToMap(JsonUtil.java:85) ~[multiapps-common-2.12.0.jar:?]
	at org.cloudfoundry.multiapps.common.util.JsonUtil.convertJsonToMap(JsonUtil.java:66) ~[multiapps-common-2.12.0.jar:?]
	at org.cloudfoundry.multiapps.common.util.JsonUtil.convertJsonToMap(JsonUtil.java:62) ~[multiapps-common-2.12.0.jar:?]
	at org.cloudfoundry.multiapps.controller.core.helpers.ApplicationEnvironmentUpdater.updateApplicationEnvironment(ApplicationEnvironmentUpdater.java:41) ~[multiapps-controller-core-1.149.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.UploadAppStep.attemptToUpdateApplicationDigest(UploadAppStep.java:201) ~[multiapps-controller-process-1.149.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.UploadAppStep.executeAsyncStep(UploadAppStep.java:87) ~[multiapps-controller-process-1.149.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.AsyncFlowableStep.executeStep(AsyncFlowableStep.java:18) ~[multiapps-controller-process-1.149.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.TimeoutAsyncFlowableStep.executeStep(TimeoutAsyncFlowableStep.java:19) ~[multiapps-controller-process-1.149.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.executeInternal(SyncFlowableStep.java:75) ~[multiapps-controller-process-1.149.1.jar:?]
Not sure what is causing the : to appear in the app-content-digest.
Kindly help trouble shoot the same.

### Your environment
*	MultiApps Controller version - 
*	MultiApps CF CLI Plugin version - 
*	which CF vendor is used - 
*	which backing services are used - 

### Steps to reproduce
Tell us how to reproduce this issue.
Create [GIST(s)](https://gist.github.com/) which is copy of your deployment and extension descriptor and link here (if applicable)

### Additional information

If you operate your own MultiApps Controller, provide all application logs. Create a [GIST(s)](https://gist.github.com/) which contains the logs. Please refrain of copying full logs here because it will make the issue hard to read.

If an multi-target app operation fails, download logs of the operation and provide them as a [GIST(s)](https://gist.github.com/).  For more details, see *download-mta-op-logs / dmol* command provided by [CF MTA Plugin](https://github.com/cloudfoundry-incubator/multiapps-cli-plugin). The most important log file is *MAIN_LOG*.

**Comment by theghost5800** [comment]
Hi @vidhyaan , Could you please provide details about used environment. 
Did you bring up by yourself multiapps-controller backend?
This error seems to be related with parsing application environment metadata related with mta deployment. It looks like someone edit application environment manually.

**Comment by Yavor16** [comment]
Due to inactivity I will close this issue
